<style>
    #nette-debug .nette-SimpleProfilePanel h2{font:11pt/1.5 sans-serif;margin:0;padding:2px 8px;background:#3484d2;color:white}
    #nette-debug .nette-SimpleProfilePanel table{width:100%}
    #nette-debug .nette-SimpleProfilePanel a{color:#333;background:transparent}
    #nette-debug .nette-SimpleProfilePanel a abbr{font-family:sans-serif;color:#999}
    #nette-debug .nette-SimpleProfilePanel pre .php-array,
    #nette-debug .nette-SimpleProfilePanel pre .php-object{color:#c16549}
</style>


<h1>Simple Profiler</h1>

<div class="nette-inner nette-SimpleProfilePanel">
    <?php
    echo $list = \Bubo\Profiler\MenuProfiler\MenuProfiler::paintCharts();

    if(is_array($list)):
        foreach($list as $image):
            if(file_exists($image)):
        ?>

        <img src="data:image/png;base64,<?php echo base64_encode(file_get_contents($image));?>" alt="" />


            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>

</div>
